// Pronunciation respellings (US-friendly) + common spelling alternatives.
// Keyed by name; merged into names.json by the generator. CAPS = stressed syllable.
export const PRON = {
// english
"Oliver":"OL-ih-ver","Henry":"HEN-ree","Theodore":"THEE-oh-dor","Jack":"JAK","William":"WIL-yum","George":"JORJ","Arthur":"AR-thur","Edward":"ED-wurd","Charles":"CHARLZ","Frederick":"FRED-rik","Alfred":"AL-frid","Walter":"WAWL-ter","Miles":"MYLZ","Graham":"GRAY-um","Dexter":"DEK-ster","Hugh":"HYOO","Cole":"KOHL","Reid":"REED","Oscar":"OS-kur","Felix":"FEE-liks","Everett":"EV-er-it","Wesley":"WES-lee","Bennett":"BEN-it","Harold":"HA-ruld","Nathaniel":"nuh-THAN-yul","Sebastian":"suh-BAS-chun","Maxwell":"MAKS-wel","Chester":"CHES-ter","Silas":"SY-lus","Rupert":"ROO-pert","Percy":"PUR-see","Warren":"WOR-in","Clifford":"KLIF-urd","Byron":"BY-run","Leonard":"LEN-urd","Ronald":"RON-uld",
"Charlotte":"SHAR-lut","Amelia":"uh-MEEL-yuh","Evelyn":"EV-uh-lin","Grace":"GRAYSS","Alice":"AL-iss","Florence":"FLOR-ints","Beatrice":"BEE-uh-triss","Harriet":"HA-ree-it","Ivy":"EYE-vee","Margaret":"MAR-gret","Eleanor":"EL-uh-nor","Rose":"ROHZ","Hazel":"HAY-zul","Winifred":"WIN-ih-fred","Maisie":"MAY-zee","Nora":"NOR-uh","Pearl":"PURL","Faye":"FAY","Emily":"EM-ih-lee","Josephine":"JOH-suh-feen","Violet":"VY-uh-lit","Audrey":"AW-dree","Poppy":"POP-ee","Cora":"KOR-uh","Edith":"EE-dith","Matilda":"muh-TIL-duh","Penelope":"puh-NEL-uh-pee","Clara":"KLA-ruh","Sylvia":"SIL-vee-uh","Iris":"EYE-riss","Millicent":"MIL-ih-sunt","Lucy":"LOO-see","Georgia":"JOR-juh","Vivienne":"VIV-ee-en","Maren":"MAH-rin","Wren":"REN",
"Riley":"RY-lee","Blake":"BLAYK","Quinn":"KWIN","Rowan":"ROH-un","Sage":"SAYJ","Alex":"AL-eks","Emerson":"EM-er-sun","Harper":"HAR-per","Ellis":"EL-iss","Aubrey":"AW-bree","Marley":"MAR-lee","Reese":"REESS",
// irish
"Liam":"LEE-um","Aiden":"AY-den","Cian":"KEE-un","Declan":"DEK-lun","Finn":"FIN","Cormac":"KOR-mak","Oisin":"uh-SHEEN","Ronan":"ROH-nun","Seamus":"SHAY-mus","Eoin":"OH-in","Padraig":"PAW-drig","Cillian":"KIL-ee-un","Fergus":"FUR-gus","Niall":"NY-ul","Conor":"KON-ur","Rory":"ROR-ee","Tadhg":"TYG","Brennan":"BREN-un","Callahan":"KAL-uh-han","Desmond":"DEZ-mund","Eamon":"AY-mun","Lorcan":"LOR-kun","Odhran":"OR-un","Senan":"SHEN-un",
"Saoirse":"SUR-shuh","Aoife":"EE-fuh","Niamh":"NEEV","Ciara":"KEE-ruh","Siobhan":"shih-VAWN","Maeve":"MAYV","Roisin":"roh-SHEEN","Orla":"OR-luh","Fiona":"fee-OH-nuh","Sinead":"shih-NAYD","Bridget":"BRIJ-it","Nuala":"NOO-uh-luh","Grainne":"GRAWN-yuh","Deirdre":"DEER-druh","Aisling":"ASH-ling","Caoimhe":"KEE-vuh","Eilis":"AY-lish","Muireann":"MWIR-un","Sorcha":"SOR-uh-kuh","Cara":"KA-ruh","Aine":"AWN-yuh","Blathnaid":"BLAW-nid","Clodagh":"KLOH-duh","Etain":"eh-TAWN",
"Kelly":"KEL-ee","Casey":"KAY-see","Shea":"SHAY","Devin":"DEV-in","Flannery":"FLAN-uh-ree","Rian":"REE-un","Sloane":"SLOHN",
// scottish
"Callum":"KAL-um","Angus":"ANG-gus","Hamish":"HAY-mish","Fraser":"FRAY-zer","Lachlan":"LOK-lun","Ewan":"YOO-un","Malcolm":"MAL-kum","Alistair":"AL-iss-ter","Duncan":"DUNG-kun","Ruaridh":"ROO-ree","Blair":"BLAIR","Gordon":"GOR-dun","Kenneth":"KEN-ith","Struan":"STROO-un","Douglas":"DUG-lus","Iain":"EE-un","Craig":"KRAYG","Finlay":"FIN-lay","Murray":"MUR-ee","Bruce":"BROOSS","Gregor":"GREG-ur","Kade":"KAYD","Ross":"ROSS","Wallace":"WOL-iss",
"Isla":"EYE-luh","Skye":"SKY","Elsie":"EL-see","Ainsley":"AYNZ-lee","Iona":"eye-OH-nuh","Mhairi":"VAH-ree","Catriona":"kuh-TREE-nuh","Kirsty":"KUR-stee","Rhona":"ROH-nuh","Effie":"EF-ee","Senga":"SENG-guh","Morag":"MOR-ag","Bonnie":"BON-ee","Greer":"GREER","Lorna":"LOR-nuh","Fenella":"fuh-NEL-uh","Davina":"duh-VEE-nuh","Elspeth":"EL-spith","Paisley":"PAYZ-lee","Ishbel":"ISH-bel","Jean":"JEEN","Nairn":"NAIRN","Sheena":"SHEE-nuh",
"Lennox":"LEN-uks","Mackenzie":"muh-KEN-zee","Islay":"EYE-luh",
// french
"Louis":"LOO-ee","Julien":"zhoo-lee-EN","Gabriel":"GAY-bree-ul","Antoine":"an-TWAHN","Lucas":"LOO-kah","Mathis":"mah-TEESS","Raphael":"RAF-eye-el","Etienne":"ay-TYEN","Olivier":"oh-lee-VYAY","Sacha":"SAH-shuh","Remy":"ray-MEE","Pascal":"pas-KAL","Florian":"FLOR-ee-un","Cedric":"SED-rik","Bastien":"bas-TYEN","Thibault":"tee-BOH","Amaury":"oh-mor-EE","Corentin":"kor-on-TAN","Gaspard":"gas-PAR","Loic":"loh-EEK","Maxime":"mak-SEEM","Aurelien":"or-ay-LYEN","Baptiste":"bap-TEEST","Sylvain":"seel-VAN",
"Camille":"kah-MEE","Chloe":"KLOH-ee","Manon":"mah-NOHN","Elise":"ay-LEEZ","Amelie":"AM-uh-lee","Margaux":"mar-GOH","Colette":"koh-LET","Sylvie":"seel-VEE","Genevieve":"ZHON-vee-ev","Aurelie":"or-ay-LEE","Delphine":"del-FEEN","Celeste":"suh-LEST","Fleur":"FLUR","Odette":"oh-DET","Solene":"soh-LEN","Noemie":"noh-ay-MEE","Ines":"ee-NESS","Lea":"LAY-uh","Adele":"uh-DEL","Sabine":"sah-BEEN","Emmanuelle":"ee-man-yoo-EL","Perrine":"peh-REEN",
"Claude":"KLOHD","Dominique":"dom-in-EEK","Rene":"reh-NAY",
// italian
"Leonardo":"lay-oh-NAR-doh","Matteo":"mah-TAY-oh","Alessandro":"ah-lay-SAHN-droh","Lorenzo":"loh-REN-zoh","Giovanni":"joh-VAH-nee","Marco":"MAR-koh","Antonio":"an-TOH-nee-oh","Francesco":"fran-CHES-koh","Luca":"LOO-kah","Dante":"DAHN-tay","Emilio":"eh-MEE-lee-oh","Fabrizio":"fah-BREET-see-oh","Giuseppe":"joo-ZEP-pay","Salvatore":"sal-vah-TOR-ay","Vincenzo":"vin-CHEN-zoh","Enzo":"EN-zoh","Cristiano":"kris-tee-AH-noh","Massimo":"MAH-see-moh","Nico":"NEE-koh","Raffaele":"raf-fah-EL-ay","Stefano":"STEF-ah-noh","Valentino":"val-en-TEE-noh","Bruno":"BROO-noh","Gian":"JAHN",
"Sofia":"soh-FEE-uh","Giulia":"JOO-lee-uh","Aurora":"aw-ROR-uh","Chiara":"kee-AH-ruh","Francesca":"fran-CHES-kuh","Valentina":"val-en-TEE-nuh","Bianca":"bee-AHN-kuh","Alessia":"ah-LES-see-uh","Martina":"mar-TEE-nuh","Serena":"suh-REE-nuh","Gaia":"GY-uh","Elena":"EL-eh-nuh","Isabella":"iz-uh-BEL-uh","Camilla":"kuh-MIL-uh","Lucia":"loo-CHEE-uh","Federica":"fed-eh-REE-kuh","Ginevra":"jee-NEV-ruh","Noemi":"noh-EM-ee","Alba":"AL-buh","Vittoria":"vit-TOR-ee-uh","Rosa":"ROH-zuh","Cecilia":"suh-SEEL-yuh","Emma":"EM-uh",
"Andrea":"AHN-dray-uh","Nicola":"nee-KOH-lah","Gioia":"JOY-uh",
// spanish
"Mateo":"mah-TAY-oh","Diego":"dee-AY-goh","Santiago":"san-tee-AH-goh","Alejandro":"ah-lay-HAHN-droh","Javier":"hah-vee-AIR","Rafael":"rah-fah-EL","Emiliano":"eh-mee-lee-AH-noh","Pablo":"PAH-bloh","Sergio":"SAIR-hee-oh","Andres":"AHN-drayss","Ignacio":"eeg-NAH-see-oh","Rodrigo":"roh-DREE-goh","Marcos":"MAR-kohs","Alonso":"ah-LOHN-soh","Cruz":"KROOZ","Joaquin":"wah-KEEN","Ramon":"rah-MOHN","Salvador":"sal-vah-DOR","Nicolas":"nee-koh-LAHS","Esteban":"es-TAY-bahn","Gael":"gah-EL","Tomas":"toh-MAHS",
"Valentina":"vah-len-TEE-nah","Isabela":"ee-sah-BEL-uh","Camila":"kah-MEE-lah","Valeria":"vah-LAIR-ee-uh","Ximena":"hee-MAY-nah","Paloma":"pah-LOH-mah","Carmen":"KAR-men","Rocio":"roh-SEE-oh","Pilar":"pee-LAR","Dolores":"doh-LOR-ess","Esperanza":"es-peh-RAHN-sah","Mercedes":"mer-SAY-dess","Guadalupe":"gwah-dah-LOO-pay","Renata":"reh-NAH-tah","Alejandra":"ah-lay-HAHN-drah","Marisol":"mah-ree-SOL","Consuelo":"kon-SWAY-loh","Aitana":"eye-TAH-nah","Julieta":"hoo-lee-AY-tah","Amaya":"ah-MY-ah","Regina":"reh-HEE-nah",
"Reyes":"RAY-ess","Trinidad":"tree-nee-DAHD",
// german
"Maximilian":"mak-sih-MIL-ee-un","Lukas":"LOO-kahs","Jonas":"YOH-nahs","Emil":"AY-mil","Anton":"AHN-ton","Fritz":"FRITS","Klaus":"KLOWSS","Otto":"OT-toh","Konrad":"KON-rahd","Dietrich":"DEE-trikh","Ansel":"AN-sul","Gerhard":"GAIR-hart","Wolfgang":"WULF-gang","Kurt":"KURT","Heinrich":"HYN-rikh","Lennard":"LEN-art","Bastian":"BAHS-tee-un","Falko":"FAHL-koh","Rainer":"RY-ner","Stefan":"SHTEF-un","Ludwig":"LOOD-vig","Norbert":"NOR-bert","Reinhard":"RYN-hart",
"Mia":"MEE-uh","Emilia":"eh-MEEL-yuh","Hanna":"HAH-nuh","Frieda":"FREE-duh","Greta":"GRAY-tuh","Ingrid":"ING-grid","Heidi":"HY-dee","Lorelei":"LOR-uh-ly","Klara":"KLAH-ruh","Elke":"EL-kuh","Annelise":"AH-nuh-lee-suh","Gisela":"GEE-zuh-luh","Katharina":"kah-tuh-REE-nuh","Liesel":"LEE-zul","Sieglinde":"zeeg-LIN-duh","Anneke":"AH-nuh-kuh","Johanna":"yoh-HAH-nuh","Marlene":"mar-LAY-nuh","Ada":"AH-duh","Elfriede":"el-FREE-duh","Petra":"PAY-truh","Sabine":"zah-BEE-nuh","Trudi":"TROO-dee","Wilhelmina":"vil-hel-MEE-nuh",
"Toni":"TOH-nee","Kai":"KY","Mika":"MEE-kuh","Nikita":"nih-KEE-tuh",
// nordic
"Magnus":"MAG-nus","Bjorn":"BYORN","Erik":"AIR-ik","Leif":"LAYF","Odin":"OH-din","Sven":"SVEN","Axel":"AK-sul","Soren":"SOR-en","Thor":"THOR","Anders":"AHN-ders","Gustav":"GUS-tahv","Nils":"NILSS","Viggo":"VIG-oh","Halvard":"HAHL-vard","Torsten":"TOR-sten","Rune":"ROO-nuh","Espen":"ES-pen","Ivar":"EE-var","Sindre":"SIN-druh","Frode":"FROH-duh","Kjell":"KYEL","Ragnar":"RAG-nar","Vidar":"VEE-dar",
"Freya":"FRAY-uh","Astrid":"AS-trid","Sigrid":"SIG-rid","Solveig":"SOL-vay","Liv":"LIV","Signe":"SIG-nuh","Elin":"EH-lin","Maja":"MY-uh","Thora":"TOR-uh","Ronja":"RON-yuh","Alva":"AHL-vuh","Saga":"SAH-guh","Hedda":"HED-uh","Tove":"TOH-vuh","Vera":"VAIR-uh","Ebba":"EB-uh","Gudrun":"GOOD-roon","Nanna":"NAH-nuh","Siv":"SEEV","Embla":"EM-bluh","Frida":"FREE-duh","Marit":"MAH-rit","Yrsa":"UR-suh",
"Ari":"AH-ree","Bo":"BOH","Loke":"LOH-kuh",
// slavic
"Nikolai":"nih-koh-LY","Ivan":"ee-VAHN","Dmitri":"duh-MEE-tree","Alexei":"uh-LEK-say","Mikhail":"mih-kah-EEL","Boris":"BOR-iss","Viktor":"VIK-tor","Sergei":"SAIR-gay","Milan":"mih-LAHN","Radek":"RAH-dek","Bogdan":"BOHG-dahn","Stanislav":"STAH-nih-slahv","Vladimir":"VLAD-ih-meer","Tomasz":"TOH-mahsh","Lukasz":"WOO-kahsh","Kazimir":"KAH-zih-meer","Marek":"MAH-rek","Andrzej":"AHND-zhay","Rostislav":"ROS-tih-slahv","Ivo":"EE-voh","Jarek":"YAH-rek","Pavel":"PAH-vel","Zoran":"ZOR-ahn",
"Natasha":"nuh-TAH-shuh","Anastasia":"an-uh-STAY-zhuh","Katarina":"kah-tuh-REE-nuh","Milena":"mih-LAY-nuh","Nadia":"NAH-dee-uh","Zofia":"ZOF-yuh","Ludmila":"lood-MEE-luh","Irina":"ee-REE-nuh","Svetlana":"svet-LAH-nuh","Bojana":"boh-YAH-nuh","Danica":"DAH-nih-tsuh","Jasna":"YAHS-nuh","Lada":"LAH-duh","Marika":"mah-REE-kuh","Nina":"NEE-nuh","Olga":"OHL-guh","Radmila":"rahd-MEE-luh","Tatiana":"tah-tee-AH-nuh","Zlata":"ZLAH-tuh","Dragana":"drah-GAH-nuh","Kalina":"kah-LEE-nuh","Mira":"MEE-ruh","Yelena":"yeh-LAY-nuh",
"Sasha":"SAH-shuh","Slavko":"SLAHV-koh","Vlada":"VLAH-duh",
// greek
"Alexander":"al-ig-ZAN-der","Nikolaos":"nih-KOH-lah-os","Dimitrios":"dih-MEE-tree-os","Georgios":"YOR-yos","Ioannis":"ee-oh-AH-nis","Andreas":"an-DRAY-us","Konstantinos":"kon-stan-TEE-nos","Theodoros":"thee-oh-DOR-os","Stavros":"STAHV-ros","Panagiotis":"pah-nah-YOH-tis","Christos":"KREES-tos","Vasilios":"vah-SEE-lee-os","Leonidas":"lee-OH-nih-das","Orion":"oh-RY-un","Apollo":"uh-POL-oh","Damianos":"dah-mee-AH-nos","Elias":"ee-LY-us","Yannis":"YAH-nis","Spyridon":"SPEE-ree-don","Achilles":"uh-KIL-eez","Marios":"MAH-ree-os","Petros":"PET-ros","Thanos":"THAH-nos","Zenon":"ZAY-non",
"Sophia":"soh-FEE-uh","Eleni":"eh-LEH-nee","Katerina":"kah-teh-REE-nuh","Maria":"muh-REE-uh","Despina":"des-PEE-nuh","Ioanna":"ee-oh-AH-nuh","Thalia":"thuh-LY-uh","Athena":"uh-THEE-nuh","Calliope":"kuh-LY-uh-pee","Daphne":"DAF-nee","Chara":"HAH-rah","Ariadne":"air-ee-AD-nee","Zoe":"ZOH-ee","Xanthe":"ZAN-thee","Melina":"muh-LEE-nuh","Ismene":"iss-MEE-nee","Danae":"DAH-nah-ay","Selene":"suh-LEE-nee","Phoebe":"FEE-bee","Theodora":"thee-oh-DOR-uh","Nefeli":"neh-FEH-lee",
"Nikos":"NEE-kos","Elia":"eh-LEE-uh","Chryssa":"KREE-suh","Arion":"AH-ree-on",
// armenian
"Aram":"ah-RAHM","Vahan":"vah-HAHN","Hovhannes":"hov-hah-NESS","Tigran":"tee-GRAHN","Armen":"ar-MEN","Narek":"nah-REK","Gevorg":"geh-VORK","Sarkis":"sar-KEESS","Hayk":"HYK","Vartan":"var-TAHN","Levon":"leh-VOHN","Ashot":"ah-SHOT","Davit":"dah-VEET","Garen":"gah-REN","Karen":"kah-REN","Mher":"MHAIR","Raffi":"RAH-fee","Sevan":"seh-VAHN","Vrej":"VREZH","Hrant":"HRAHNT","Areg":"ah-REG","Grigor":"gree-GOR","Nubar":"noo-BAR","Shant":"SHAHNT",
"Ani":"AH-nee","Nairi":"NY-ree","Lucine":"loo-SEEN","Anahit":"ah-nah-HEET","Arpine":"ar-pee-NEH","Mariam":"mah-ree-AHM","Sona":"SOH-nah","Nare":"NAH-reh","Gohar":"goh-HAR","Siran":"see-RAHN","Takouhi":"tah-koo-HEE","Zabel":"zah-BEL","Armine":"ar-mee-NEH","Hasmik":"hahs-MEEK","Nvard":"nuh-VARD","Shushan":"shoo-SHAHN","Vart":"VART","Lusntag":"loos-nuh-TAHG","Maral":"mah-RAHL","Sose":"SOH-seh","Arev":"ah-REV","Knar":"kuh-NAR","Yeva":"YEH-vah","Zvart":"zuh-VART","Van":"VAHN",
// hebrew
"Noah":"NOH-uh","Ethan":"EE-thun","Asher":"ASH-er","Levi":"LEE-vy","Eli":"EE-ly","Caleb":"KAY-lub","Micah":"MY-kuh","Gideon":"GID-ee-un","Aaron":"AIR-un","Nathan":"NAY-thun","Isaac":"EYE-zik","Jonah":"JOH-nuh","Boaz":"BOH-az","Ezra":"EZ-ruh","Reuben":"ROO-bin","Simon":"SY-mun","Amos":"AY-mus","Malachi":"MAL-uh-ky","Tobias":"toh-BY-us","Zev":"ZEV","Nadav":"nah-DAHV","Yosef":"YOH-sef","Eitan":"ay-TAHN",
"Abigail":"AB-ih-gayl","Hannah":"HAN-uh","Naomi":"nay-OH-mee","Leah":"LEE-uh","Miriam":"MEER-ee-um","Talia":"TAHL-yuh","Shira":"SHEE-rah","Adina":"ah-DEE-nuh","Eliana":"el-ee-AH-nuh","Noa":"NOH-uh","Tamar":"tah-MAR","Yael":"yah-EL","Dalia":"DAHL-yuh","Ayelet":"ah-YEH-let","Batya":"BAHT-yah","Carmel":"kar-MEL","Liora":"lee-OR-uh","Maayan":"mah-ah-YAHN","Rivka":"RIV-kuh","Shoshana":"shoh-SHAH-nuh","Tova":"TOH-vuh","Yaffa":"YAH-fuh","Zohar":"ZOH-har","Netta":"NET-uh",
"Ariel":"AIR-ee-el","Noam":"NOH-um","Shai":"SHY","Yuval":"yoo-VAHL",
// arabic
"Omar":"OH-mar","Yusuf":"YOO-suf","Zayd":"ZAYD","Karim":"kah-REEM","Tariq":"TAH-rik","Bilal":"bih-LAHL","Amir":"ah-MEER","Rashid":"rah-SHEED","Hamza":"HAM-zuh","Idris":"ID-riss","Malik":"MAH-lik","Nabil":"nah-BEEL","Samir":"sah-MEER","Faris":"FAH-riss","Jamal":"jah-MAHL","Khalil":"kah-LEEL","Sami":"SAH-mee","Ziad":"zee-AHD","Anwar":"AHN-war","Basil":"BAH-sil","Fadi":"FAH-dee","Nasir":"NAH-seer","Rami":"RAH-mee","Wael":"WAH-el",
"Layla":"LAY-luh","Amira":"ah-MEER-uh","Yasmin":"YAZ-min","Zara":"ZAH-ruh","Aisha":"eye-EE-shuh","Farah":"FAH-ruh","Salma":"SAHL-muh","Rania":"RAH-nee-uh","Nour":"NOOR","Hana":"HAH-nuh","Lina":"LEE-nuh","Maryam":"MAR-yuhm","Dalia":"DAH-lee-uh","Iman":"ee-MAHN","Jana":"JAH-nuh","Rima":"REE-muh","Samira":"sah-MEER-uh","Widad":"wih-DAHD","Zaina":"ZY-nuh","Amal":"AH-mul","Bushra":"BOOSH-ruh","Huda":"HOO-duh","Najwa":"NAJ-wuh","Sana":"SAH-nuh","Rida":"REE-duh",
// persian
"Kian":"kee-AHN","Cyrus":"SY-rus","Darius":"DAIR-ee-us","Arash":"ah-RAHSH","Kaveh":"kah-VEH","Bijan":"bee-ZHAHN","Farhad":"far-HAHD","Sina":"SEE-nuh","Rostam":"ROS-tahm","Kourosh":"koo-ROHSH","Nima":"NEE-mah","Babak":"bah-BAHK","Siavash":"see-ah-VAHSH","Parsa":"par-SAH","Ramin":"rah-MEEN","Kamran":"kahm-RAHN","Behrouz":"beh-ROOZ","Jamshid":"jahm-SHEED","Sohrab":"soh-RAHB","Ardeshir":"ar-deh-SHEER","Farbod":"far-BOHD","Mani":"MAH-nee","Roozbeh":"ROOZ-beh","Aria":"AH-ree-uh",
"Roya":"ROY-uh","Shirin":"shee-REEN","Nasrin":"nahs-REEN","Anahita":"ah-nah-HEE-tah","Darya":"DAR-yuh","Setareh":"seh-tah-REH","Mahsa":"MAH-sah","Parisa":"pah-REE-sah","Ava":"AH-vah","Golnar":"gohl-NAR","Nazanin":"nah-zah-NEEN","Roxana":"rok-SAH-nuh","Soraya":"soh-RY-uh","Tara":"TAH-ruh","Azadeh":"ah-zah-DEH","Bahar":"bah-HAR","Laleh":"LAH-leh","Mahnaz":"mah-NAHZ","Simin":"see-MEEN","Niloufar":"nee-loo-FAR","Parvaneh":"par-vah-NEH","Sahar":"sah-HAR","Yalda":"YAHL-dah",
// turkish
"Emir":"eh-MEER","Kaan":"KAHN","Deniz":"deh-NEEZ","Mert":"MERT","Baris":"bah-RUSH","Arda":"AR-dah","Cem":"JEM","Efe":"EH-feh","Berk":"BERK","Can":"JAHN","Ozan":"oh-ZAHN","Tolga":"TOHL-gah","Volkan":"vohl-KAHN","Kerem":"keh-REM","Alp":"AHLP","Bora":"boh-RAH","Egemen":"EH-geh-men","Sinan":"see-NAHN","Yigit":"yee-EET","Onur":"oh-NOOR","Umut":"oo-MOOT","Kaya":"KY-ah","Tarik":"TAH-rik",
"Elif":"eh-LEEF","Zeynep":"ZAY-nep","Defne":"DEF-neh","Ayla":"EYE-lah","Ece":"EH-jeh","Derya":"DER-yah","Melisa":"meh-LEE-sah","Sude":"SOO-deh","Yasemin":"yah-seh-MEEN","Cansu":"JAHN-soo","Ela":"EH-lah","Ipek":"ee-PEK","Lale":"LAH-leh","Nazli":"NAHZ-luh","Selin":"seh-LEEN","Ceylan":"jay-LAHN","Damla":"DAHM-lah","Esra":"ES-rah","Gizem":"gee-ZEM","Irmak":"ur-MAHK","Pinar":"puh-NAR","Sena":"SEH-nah","Yaren":"YAH-ren","Nur":"NOOR",
// indian
"Arjun":"AR-jun","Aarav":"AH-rav","Vihaan":"vih-HAHN","Rohan":"ROH-hun","Ishaan":"ih-SHAHN","Krishna":"KRISH-nuh","Aditya":"uh-DIT-yuh","Dev":"DEV","Kabir":"kah-BEER","Reyansh":"ray-AHNSH","Ved":"VED","Ansh":"AHNSH","Advait":"ud-VYT","Nikhil":"nih-KEEL","Om":"OHM","Rudra":"ROOD-ruh","Shaan":"SHAHN","Tarun":"TAH-run","Yash":"YAHSH","Neel":"NEEL","Ajay":"uh-JAY","Kiran":"kih-RAHN","Manav":"MAH-nav","Varun":"VAH-run",
"Aanya":"AHN-yuh","Diya":"DEE-yuh","Priya":"PREE-yuh","Anaya":"uh-NY-uh","Ishani":"ih-SHAH-nee","Kavya":"KAHV-yuh","Meera":"MEE-ruh","Saanvi":"SAHN-vee","Aditi":"UD-ih-tee","Riya":"REE-uh","Sitara":"sih-TAH-ruh","Anika":"UH-nih-kuh","Ira":"EE-ruh","Kiara":"kee-AH-ruh","Nisha":"NEE-shuh","Amara":"uh-MAH-ruh","Devi":"DAY-vee","Lata":"LAH-tuh","Pooja":"POO-juh","Rani":"RAH-nee","Shreya":"SHRAY-uh","Uma":"OO-muh","Veena":"VEE-nuh","Jyoti":"JYOH-tee","Amar":"UH-mar","Nihal":"nih-HAHL",
// japanese
"Haruki":"hah-ROO-kee","Ren":"REN","Sota":"SOH-tah","Yuto":"YOO-toh","Kaito":"KY-toh","Riku":"REE-koo","Sora":"SOH-rah","Haru":"HAH-roo","Takumi":"tah-KOO-mee","Hiroshi":"hee-ROH-shee","Kenji":"KEN-jee","Daichi":"DY-chee","Yuki":"YOO-kee","Akira":"ah-KEE-rah","Ryo":"RYOH","Sho":"SHOH","Itsuki":"eet-SOO-kee","Minato":"mee-NAH-toh","Asahi":"ah-SAH-hee","Kenta":"KEN-tah","Naoki":"nah-OH-kee","Tsubasa":"tsoo-BAH-sah","Hayato":"hah-YAH-toh","Makoto":"mah-KOH-toh",
"Sakura":"sah-KOO-rah","Yui":"YOO-ee","Hana":"HAH-nah","Aoi":"AH-oh-ee","Mei":"MAY","Rin":"REEN","Yuna":"YOO-nah","Hina":"HEE-nah","Emi":"EH-mee","Kokoro":"koh-KOH-roh","Mio":"MEE-oh","Akari":"ah-KAH-ree","Nana":"NAH-nah","Momo":"MOH-moh","Ayaka":"ah-YAH-kah","Haruka":"hah-ROO-kah","Rei":"RAY","Tsubaki":"tsoo-BAH-kee","Kaede":"kah-EH-deh","Miyu":"MEE-yoo","Nao":"NAH-oh","Yuzuki":"yoo-ZOO-kee","Hikaru":"hee-KAH-roo",
// chinese
"Wei":"WAY","Hao":"HOW","Jun":"JOON","Ming":"MING","Lei":"LAY","Feng":"FUNG","Bo":"BWOH","Chen":"CHUN","Kang":"KAHNG","Long":"LOHNG","Peng":"PUNG","Tao":"TOW","Yang":"YAHNG","Zhi":"JUR","Bin":"BEEN","Cheng":"CHUNG","Hong":"HOHNG","Jian":"JYEN","Kai":"KY","Sheng":"SHUNG","Xiang":"SHYAHNG","Yong":"YOHNG","Zhen":"JUN","Jing":"JING",
"Mei":"MAY","Ling":"LING","Hua":"HWAH","Yan":"YEN","Xia":"SHYAH","Lan":"LAHN","Fang":"FAHNG","Li":"LEE","Na":"NAH","Qing":"CHING","Wen":"WUN","Ying":"YING","Bai":"BY","Chun":"CHWUN","Hui":"HWAY","Jiao":"JYOW","Min":"MEEN","Ping":"PING","Rou":"ROH","Xue":"SHWEH","Yun":"YOON","Zhu":"JOO","Yi":"EE","Xin":"SHEEN","Jia":"JYAH","An":"AHN","Le":"LUH","Yu":"YOO",
// korean
"Min-jun":"min-JOON","Seo-jun":"suh-JOON","Do-yun":"doh-YOON","Ji-ho":"jee-HOH","Ha-joon":"hah-JOON","Eun-woo":"un-WOO","Si-woo":"see-WOO","Joon-ho":"joon-HOH","Tae-yang":"tay-YAHNG","Ji-hoon":"jee-HOON","Hyun-woo":"hyun-WOO","Min-ho":"min-HOH","Seung":"SUNG","Jin-woo":"jin-WOO","Woo-jin":"woo-JIN","Sung-min":"sung-MIN","Yun-seo":"yoon-SUH","Kang":"KAHNG","Dae":"DAY","Ho":"HOH","Jae":"JAY","Nam":"NAHM","Young":"YUNG",
"Seo-yeon":"suh-YUN","Ji-woo":"jee-WOO","Ha-eun":"hah-UN","Seo-ah":"suh-AH","Ji-a":"jee-AH","Soo-ah":"soo-AH","Ye-jin":"yeh-JIN","Yu-na":"yoo-NAH","Da-eun":"dah-UN","Chae-won":"chay-WON","Ji-min":"jee-MIN","Ha-yoon":"hah-YOON","Eun-ji":"un-JEE","Min-seo":"min-SUH","Su-bin":"soo-BIN","Ye-eun":"yeh-UN","Hana":"HAH-nah","Bo-ram":"boh-RAHM","Sae-rom":"say-ROHM","A-ri":"AH-ree","Mi-rae":"mee-RAY","Na-yeon":"nah-YUN","So-ra":"soh-RAH","Yeong":"YUNG","Yu-jin":"yoo-JIN",
// african
"Kwame":"KWAH-may","Jabari":"jah-BAH-ree","Amari":"ah-MAH-ree","Sekou":"SAY-koo","Chike":"CHEE-kay","Themba":"TEM-bah","Kofi":"KOH-fee","Zuberi":"zoo-BEH-ree","Baraka":"bah-RAH-kah","Tafari":"tah-FAH-ree","Simba":"SIM-bah","Jelani":"jeh-LAH-nee","Kato":"KAH-toh","Oba":"OH-bah","Chuma":"CHOO-mah","Bakari":"bah-KAH-ree","Dumisani":"doo-mee-SAH-nee","Femi":"FEH-mee","Nuru":"NOO-roo","Sefu":"SEH-foo","Tendai":"ten-DYE","Uzoma":"oo-ZOH-mah","Yohance":"yoh-HAHN-say","Zola":"ZOH-lah",
"Amara":"ah-MAH-rah","Zuri":"ZOO-ree","Nia":"NEE-ah","Ayana":"eye-AH-nah","Imani":"ee-MAH-nee","Sanaa":"sah-NAH","Thandiwe":"tahn-DEE-way","Folami":"foh-LAH-mee","Ada":"AH-dah","Chiamaka":"chee-ah-MAH-kah","Aisha":"eye-EE-shah","Kesse":"KES-say","Nala":"NAH-lah","Oni":"OH-nee","Sauda":"sah-OO-dah","Zalika":"zah-LEE-kah","Amina":"ah-MEE-nah","Dalila":"dah-LEE-lah","Halima":"hah-LEE-mah","Kamaria":"kah-MAH-ree-ah","Makena":"mah-KEH-nah","Sisi":"SEE-see","Bahati":"bah-HAH-tee",
// hawaiian
"Kai":"KY","Keanu":"kay-AH-noo","Ikaika":"ee-KY-kah","Makoa":"mah-KOH-ah","Keoni":"kay-OH-nee","Kekoa":"keh-KOH-ah","Manu":"MAH-noo","Koa":"KOH-ah","Nainoa":"ny-NOH-ah","Kaimana":"ky-MAH-nah","Lono":"LOH-noh","Palani":"pah-LAH-nee","Kanoa":"kah-NOH-ah","Akoni":"ah-KOH-nee","Nohea":"noh-HEH-ah","Kale":"KAH-lay","Kimo":"KEE-moh","Lani":"LAH-nee","Mele":"MEH-lay","Pono":"POH-noh",
"Leilani":"lay-LAH-nee","Malia":"mah-LEE-ah","Nalani":"nah-LAH-nee","Kaila":"KY-lah","Alana":"ah-LAH-nah","Moana":"moh-AH-nah","Noelani":"noh-eh-LAH-nee","Kalani":"kah-LAH-nee","Iolana":"ee-oh-LAH-nah","Ilima":"ee-LEE-mah","Kailani":"ky-LAH-nee","Lokelani":"loh-keh-LAH-nee","Anela":"ah-NEH-lah","Healani":"heh-AH-lah-nee","Kapua":"kah-POO-ah","Luana":"loo-AH-nah","Mahina":"mah-HEE-nah","Nani":"NAH-nee","Palila":"pah-LEE-lah","Ulani":"oo-LAH-nee","Wailani":"wy-LAH-nee","Kiele":"kee-EH-lay","Pua":"POO-ah","Hoku":"HOH-koo","Alaula":"ah-lah-OO-lah",
// american
"Mason":"MAY-sun","Logan":"LOH-gun","Jackson":"JAK-sun","Carter":"KAR-ter","Hunter":"HUN-ter","Wyatt":"WY-ut","Grayson":"GRAY-sun","Colton":"KOHL-tun","Hudson":"HUD-sun","Brayden":"BRAY-den","Landon":"LAN-dun","Easton":"EE-stun","Bryce":"BRYSS","Cooper":"KOO-per","Parker":"PAR-ker","Ryder":"RY-der","Beckett":"BEK-it","Tucker":"TUK-er","Weston":"WES-tun","Chase":"CHAYSS","Brody":"BROH-dee","Kayden":"KAY-den","Maverick":"MAV-rik","Bentley":"BENT-lee","Zane":"ZAYN","Tanner":"TAN-er","Jaxon":"JAK-sun","Ryker":"RY-ker",
"Addison":"AD-ih-sun","Peyton":"PAY-tun","Brooklyn":"BRUUK-lin","Kinsley":"KINZ-lee","Everly":"EV-er-lee","Paisley":"PAYZ-lee","Reagan":"RAY-gun","Kennedy":"KEN-uh-dee","Aubree":"AW-bree","Skylar":"SKY-ler","Emberly":"EM-ber-lee","Presley":"PREZ-lee","Oakley":"OHK-lee","Marlowe":"MAR-loh","Sawyer":"SOY-er","Blakely":"BLAYK-lee","Adalyn":"AD-uh-lin","Kaylee":"KAY-lee","Journee":"JUR-nee","Charleigh":"CHAR-lee","Hadley":"HAD-lee","Raelynn":"RAY-lin","Jordan":"JOR-dun","Taylor":"TAY-ler","Morgan":"MOR-gun","Avery":"AY-vuh-ree","Kendall":"KEN-dul","Dakota":"duh-KOH-tuh","Phoenix":"FEE-niks","River":"RIV-er","Justice":"JUS-tiss",
// russian
"Aleksandr":"ah-lek-SAHN-dr","Maksim":"mak-SEEM","Artyom":"ar-TYOM","Dmitriy":"DMEE-tree","Yaroslav":"yah-roh-SLAHV","Vladislav":"vlah-dee-SLAHV","Andrei":"ahn-DRAY","Timofey":"tee-mah-FAY","Kirill":"kee-REEL","Oleg":"ah-LEG","Igor":"EE-gor","Grigoriy":"gree-GOR-ee","Yuri":"YOO-ree","Roman":"roh-MAHN","Fyodor":"FYOH-dor","Vadim":"vah-DEEM","Lev":"LYEV","Gleb":"GLEB","Semyon":"seem-YOHN","Vsevolod":"VSYEH-vah-lot","Ilya":"eel-YAH","Konstantin":"kon-stahn-TEEN","Yegor":"yeh-GOR",
"Ekaterina":"yeh-kah-teh-REE-nah","Anastasiya":"ah-nah-stah-SEE-yah","Yekaterina":"yeh-kah-teh-REE-nah","Polina":"pah-LEE-nah","Sofiya":"sah-FEE-yah","Alina":"ah-LEE-nah","Kseniya":"KSEH-nee-yah","Yuliya":"YOO-lee-yah","Marina":"mah-REE-nah","Galina":"gah-LEE-nah","Larisa":"lah-REE-sah","Oksana":"ahk-SAH-nah","Tatyana":"taht-YAH-nah","Alyona":"ahl-YOH-nah","Varvara":"var-VAH-rah","Zinaida":"zee-nah-EE-dah","Raisa":"rah-EE-sah","Lyudmila":"lyood-MEE-lah","Nadezhda":"nah-DEZH-dah","Vasilisa":"vah-see-LEE-sah","Darya":"DAR-yah","Yevgeniya":"yev-GEH-nee-yah","Snezhana":"sneh-ZHAH-nah","Zhenya":"ZHEN-yah","Valya":"VAHL-yah","Slava":"SLAH-vah",
// polish
"Jakub":"YAH-koob","Szymon":"SHUH-mon","Kacper":"KAHTS-per","Filip":"FEE-leep","Wojciech":"VOY-chekh","Mateusz":"mah-TEH-oosh","Bartosz":"BAR-tosh","Krzysztof":"KSHISH-tof","Tomasz":"TOH-mahsh","Michal":"MEE-khahw","Grzegorz":"GZHEH-gosh","Piotr":"PYOTR","Mikolaj":"mee-KOH-wy","Dawid":"DAH-veed","Jan":"YAHN","Aleksander":"ah-lek-SAHN-der","Marek":"MAH-rek","Pawel":"PAH-vew","Zbigniew":"ZBIG-nyev","Henryk":"HEN-rik","Kamil":"KAH-meel","Oskar":"OS-kar","Wiktor":"VEEK-tor",
"Zofia":"ZOH-fyah","Julia":"YOO-lyah","Maja":"MY-ah","Lena":"LEH-nah","Alicja":"ah-LEETS-yah","Wiktoria":"veek-TOR-yah","Aleksandra":"ah-lek-SAHN-drah","Natalia":"nah-TAHL-yah","Gabriela":"gah-bree-EH-lah","Kinga":"KEEN-gah","Agnieszka":"ahg-NYESH-kah","Malgorzata":"mahw-goh-ZHAH-tah","Katarzyna":"kah-tah-ZHUH-nah","Ewa":"EH-vah","Iwona":"ee-VOH-nah","Kasia":"KAH-shah","Bozena":"boh-ZHEH-nah","Danuta":"dah-NOO-tah","Halina":"hah-LEE-nah","Jadwiga":"yahd-VEE-gah","Weronika":"veh-roh-NEE-kah","Zuzanna":"zoo-ZAH-nah","Karolina":"kah-roh-LEE-nah","Oliwia":"oh-LEE-vyah","Nikodem":"nee-KOH-dem","Kris":"KREESS",
// portuguese
"Miguel":"mee-GEL","Joao":"zhwown","Pedro":"PEH-droo","Tiago":"tee-AH-goo","Gustavo":"goosh-TAH-voo","Bernardo":"ber-NAR-doo","Vicente":"vee-SEN-teh","Diogo":"dee-OH-goo","Henrique":"en-REE-keh","Thiago":"tee-AH-goo","Caio":"KY-oo","Duarte":"doo-AR-teh","Afonso":"ah-FON-soo","Nuno":"NOO-noo","Vasco":"VAHSH-koo","Ravi":"RAH-vee","Davi":"dah-VEE","Murilo":"moo-REE-loo",
"Beatriz":"bee-ah-TREESH","Mariana":"mah-ree-AH-nah","Leonor":"lay-oh-NOR","Matilde":"mah-TEEL-deh","Carolina":"kah-roh-LEE-nah","Catarina":"kah-tah-REE-nah","Rita":"REE-tah","Luana":"loo-AH-nah","Manuela":"mah-noo-EH-lah","Helena":"eh-LEH-nah","Joana":"zhoo-AH-nah","Vitoria":"vee-TOR-yah","Laura":"LOW-rah","Yara":"YAH-rah",
// vietnamese
"Minh":"MING","Bao":"BOW","Duc":"DUUK","Khang":"KAHNG","Nam":"NAHM","Phuc":"FOOK","Quang":"KWAHNG","Son":"SUN","Tuan":"TWAHN","Vinh":"VING","Hung":"HUUNG","Khanh":"KAHN","Thanh":"TAHN","Trung":"CHOONG","Anh":"AHN","Dung":"ZOONG","Hoang":"HWAHNG","Kiet":"KYET","Phong":"FAWNG","Tai":"TY","Duy":"ZWEE","Nghia":"NGYAH","Nhan":"NYAHN","Hai":"HY","Tam":"TAHM",
"Linh":"LING","Mai":"MY","Ngoc":"NAWP","Huong":"HUUNG","Lan":"LAHN","Thao":"TOW","Trang":"CHAHNG","Yen":"YEN","Chi":"CHEE","Dao":"ZOW","Hoa":"HWAH","Kim":"KEEM","My":"MEE","Nhi":"NYEE","Phuong":"FUUNG","Quyen":"KWEN","Thu":"TOO","Tuyet":"TWYET","Van":"VAHN","Bich":"BIK","Diep":"ZYEP","Ha":"HAH","Suong":"SUUNG",
// filipino
"Angelo":"AHN-heh-loh","Emmanuel":"eh-MAHN-well","Jose":"hoh-SAY","Ramon":"rah-MOHN","Carlos":"KAR-los","Bayani":"bah-YAH-nee","Dakila":"dah-KEE-lah","Makisig":"mah-KEE-sig","Amado":"ah-MAH-doh","Danilo":"dah-NEE-loh","Ernesto":"er-NES-toh","Rizal":"ree-SAHL","Bautista":"bow-TEES-tah","Liwanag":"lee-WAH-nahg","Tala":"TAH-lah","Kidlat":"KEED-laht","Bagwis":"BAHG-wees",
"Cristina":"kris-TEE-nah","Corazon":"koh-rah-SOHN","Luzviminda":"looz-vee-MEEN-dah","Dalisay":"dah-LEE-sy","Ligaya":"lee-GY-ah","Liwayway":"lee-WY-wy","Marikit":"mah-REE-kit","Perlas":"PER-lahs","Diwata":"dee-WAH-tah","Bituin":"bee-TOO-in","Amihan":"ah-MEE-hahn","Halina":"hah-LEE-nah","Malaya":"mah-LY-ah","Sinag":"SEE-nahg","Reyna":"RAY-nah","Mahalia":"mah-HAH-lee-ah","Bulan":"BOO-lahn","Hiraya":"hee-RY-ah","Ana":"AH-nah","Angela":"AN-jeh-lah",
};
export const ALTS = {
"Theodore":"Theodor, Teddy","Frederick":"Fredrick, Frederic","Oscar":"Oskar","Sebastian":"Sebastián","Nathaniel":"Nathanael","Evelyn":"Evelynn, Eveline","Beatrice":"Beatrix","Eleanor":"Elinor, Eleanora","Josephine":"Joséphine","Aiden":"Aidan, Ayden","Niamh":"Neve","Saoirse":"Seersha","Aoife":"Eefa","Caoimhe":"Keeva","Sinead":"Shinead","Isla":"Islay","Sophia":"Sofia","Sofia":"Sophia","Katerina":"Katarina, Catherine","Katarina":"Catherine, Katarzyna","Maria":"Mariah, Marya","Anastasia":"Anastasiya","Anastasiya":"Anastasia","Nikolai":"Nicolai, Nikolay","Ekaterina":"Yekaterina, Catherine","Zofia":"Sofia","Yuliya":"Yulia, Julia","Aleksandr":"Alexander","Aleksandra":"Alexandra","Dmitriy":"Dmitri, Dmitry","Noah":"Noe","Isaac":"Izaak, Isaak","Hannah":"Hanna","Eliana":"Elliana","Ariel":"Arielle","Yasmin":"Jasmine, Yasmine","Layla":"Laila, Leila","Amira":"Ameera","Aisha":"Aicha, Ayesha","Zara":"Zahra","Nour":"Noor","Maryam":"Mariam, Miriam","Kian":"Keon, Cian","Roxana":"Roxanne, Roshanak","Soraya":"Suraya","Aria":"Arya","Jakub":"Jacob","Szymon":"Simon","Kacper":"Casper, Kasper","Michal":"Michael","Piotr":"Peter","Mikolaj":"Nicholas","Zuzanna":"Susanna","Katarzyna":"Katherine","Joao":"John","Miguel":"Michael","Tiago":"Thiago, James","Jose":"Joseph","Vitoria":"Victoria","Sakura":"Sakurako","Yuki":"Yūki","Haru":"Haruto","Aoi":"Aoii","Mei":"Mai","Kai":"Kaii","Aarav":"Aryan","Priya":"Priyah","Meera":"Mira","Diya":"Diyah","Mateo":"Matteo, Matthew","Sofia ":"Sophia","Isabela":"Isabella","Camila":"Camilla, Kamila","Valentina":"Valentine","Alejandro":"Alexander","Mason":"Mayson","Jaxon":"Jackson, Jaxson","Kayden":"Caden, Kaden","Brayden":"Braden, Braiden","Aubree":"Aubrey, Aubrie","Adalyn":"Adaline, Adalynn","Raelynn":"Raelyn, Raylynn","Peyton":"Payton","Skylar":"Skyler, Schuyler",
};
